// File generated by FlutterFire CLI for project `babybloom-9d7e6`.
// ignore_for_file: type=lint
//
// To refresh: `dart run flutterfire_cli:flutterfire configure --yes`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example: `await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'run `dart run flutterfire_cli:flutterfire configure`.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-mGlttiwy4sdzAUouM9gRmBZU96MvIU4',
    appId: '1:40857057813:web:a07cd34dd8bbc3e2602c1c',
    messagingSenderId: '40857057813',
    projectId: 'babybloom-9d7e6',
    authDomain: 'babybloom-9d7e6.firebaseapp.com',
    storageBucket: 'babybloom-9d7e6.firebasestorage.app',
    measurementId: 'G-N58H285NSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKLnpHmGXYQnbL_SfrmDuW3ZSK1wJ4sRM',
    appId: '1:40857057813:android:5b36c3a9633a0378602c1c',
    messagingSenderId: '40857057813',
    projectId: 'babybloom-9d7e6',
    storageBucket: 'babybloom-9d7e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApm4uSK8SotA9AG_i4xFnEk4O9nBjHWjE',
    appId: '1:40857057813:ios:0941eca7381159b7602c1c',
    messagingSenderId: '40857057813',
    projectId: 'babybloom-9d7e6',
    storageBucket: 'babybloom-9d7e6.firebasestorage.app',
    iosBundleId: 'com.example.mamabloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApm4uSK8SotA9AG_i4xFnEk4O9nBjHWjE',
    appId: '1:40857057813:ios:0941eca7381159b7602c1c',
    messagingSenderId: '40857057813',
    projectId: 'babybloom-9d7e6',
    storageBucket: 'babybloom-9d7e6.firebasestorage.app',
    iosBundleId: 'com.example.mamabloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-mGlttiwy4sdzAUouM9gRmBZU96MvIU4',
    appId: '1:40857057813:web:acbdd69a79e64656602c1c',
    messagingSenderId: '40857057813',
    projectId: 'babybloom-9d7e6',
    authDomain: 'babybloom-9d7e6.firebaseapp.com',
    storageBucket: 'babybloom-9d7e6.firebasestorage.app',
    measurementId: 'G-ZH8JQSBW87',
  );

}